export const HOME_VIDEOS_SUCCESS='HOME_VIDEOS_SUCCESS'
export const HOME_VIDEOS_FAIL='HOME_VIDEOS_FAIL'
export const HOME_VIDEOS_REQUEST='HOME_VIDEOS_REQUEST'

export const CLICKED_VIDEO_FETCH  = "CLICKED_VIDEO_FETCH"
export const CLICKED_VIDEO_SUCCESS  = "CLICKED_VIDEO_SUCCESS"
export const CLICKED_VIDEO_FAIL  = "CLICKED_VIDEO_FAIL"

export const  CHANNEL_DETAILS_FAIL= "CHANNEL_DETAILS_FAIL"
 export const CHANNEL_DETAILS_REQUEST = "CHANNEL_DETAILS_REQUEST"
 export const CHANNEL_DETAILS_SUCCESS="CHANNEL_DETAILS_SUCCESS"


 export const  COMMENTS_DETAILS_FAIL= "COMMENTS_DETAILS_FAIL"
 export const COMMENTS_DETAILS_REQUEST = "COMMENTS_DETAILS_REQUEST"
 export const COMMENTS_DETAILS_SUCCESS="COMMENTS_DETAILS_SUCCESS"


 export const RELATED_VIDEO_SUCCESS = "RELATED_VIDEO_SUCCESS"
 export const RELATED_VIDEO_REQUEST = "RELATED_VIDEO_REQUEST"
 export const RELATED_VIDEO_FAIL = "RELATED_VIDEO_FAIL"


 
 export const SEARCH_VIDEO_SUCCESS = "SEARCH_VIDEO_SUCCESS"
 export const SEARCH_VIDEO_REQUEST = "SEARCH_VIDEO_REQUEST"
 export const SEARCH_VIDEO_FAIL = "SEARCH_VIDEO_FAIL"



 export const  CHANNEL_VIDEOS_SUCCESS = "CHANNEL_VIDEOS_SUCCESS"
 export const  CHANNEL_VIDEOS_FAIL = " CHANNEL_VIDEOS_FAIL"
 export const  CHANNEL_VIDEOS_REQUEST = "CHANNEL_VIDEOS_REQUEST"